development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 837442c904d7b579c6c98618efa4b892abb377865f6e9507070787425fcb8376c5ccc52c85c6fb9a47004160e6d2b9e066bfbaa90875b92766a1e7ecd61889e7

test:
  domain_name: example.com
  secret_key_base: 8489bb21c9497da574dcb42fea4e15d089606d196e367f6f4e166acb281ddf3bf4d7fdb944390c721658de5b590dbde8e8848c2eaff9acf618bf48c4a43adb08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
